### ISSUE TITLE
Complex authorization with schema stitching

### ISSUE THREAD

**Issue by tsteenkamp** [gmac/schema-stitching-demos#25] opened 2021-02-04 15:01 UTC
Hi, big thanks first of all to all contributors to graphql-tools and this awesome handbook repo. I was hesitating going the apollo federation route for quite some time and for good reason it appears.

The only big question I have still left is how to handle complex authorization requirements with a schema gateway and the graphql services behind it. If we stick to the shopping scenario, how would one handle the following in a good way?

The desired gateway schema should look similar to this: 

```
type User {
  id: ID!
  ownedStorefronts: [Storefront]!
}

type Storefront {
  id: ID!
  name: String!
  owners: [User]!
  products: [Product]!
}

type Product {
  upc: ID!
  storefront: Storefront!
  name: String!
  price: Float!
  purchasingPrice: Float!
}

type Mutation  {
  updateProductPrice(upc: ID!, price: Float!): Product
}
```

In this case only users who own the product via the intermediate storefront relation should be able to update its price or see its `purchasingPrice`. But since the product service has only the storefront foreign ID to work with it knows nothing about users and therefore cannot check if the current user is actually allowed to update the product.

Since the number of products a user can own could become quite large it's not feasable to store this information in the user token I fear.

To handle the logic for the authorization in the gateway service could be possible I guess, but feels wrong too. That's kinda what we want to avoid with schema stitching in the first place, right? ;)

All I can think of right now is to send a request to the other service(s) from inside the product service resolvers. Would that be the best way to handle it or am I missing something obvious?

I hope this is the right place to ask these kind of questions and thanks in advance for any ideas or feedback.

**Comment by gmac** [comment] 2021-02-05 03:53
@tsteenkamp Thanks for the question! It's a good one, and it's been asked before so it's on my list to eventually add a chapter that covers it. The good news is that it's not exceptionally difficult to handle auth. Here's how:

1. In the gateway server, pull any auth information out of the user request and add that into the GraphQL context object that is built for the request.

```js
app.use(
  '/graphql',
  graphqlHTTP(async (request, response, graphQLParams) => ({
    schema: MyGraphQLSchema,
    context: {
      // extract "Bearer mytoken" into GraphQL context...
      userAuthToken: request.headers.authorization.split(' ').pop(),
    }
  })),
);
```

2. In your remote executors, you will receive the GraphQL context object as [one of the argument fields](https://github.com/gmac/schema-stitching-handbook/blob/master/combining-local-and-remote-schemas/lib/make_remote_executor.js#L9). So, it's just a matter of transferring auth information from the gateway GraphQL context into the subservice request headers. It'd look something like this:

```js
function makeRemoteExecutor(url) {
  return async ({ document, variables, context }) => {
    const query = typeof document === 'string' ? document : print(document);
    const fetchResult = await fetch(url, {
      method: 'POST',
      headers: { 
        'Authorization': `Bearer ${context.userAuthToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query, variables }),
    });
    return fetchResult.json();
  };
};
```

That should be it! Now your subservice will receive the same information that the gateway did, and it can make its own localized decisions about how to handle the request.

**Comment by gmac** [comment] 2021-02-05 04:01
Okay! I've just linked to the above comment as an appendix in the main table of contents. Hopefully folks will be able to find this thread for the answer until I get around to writing a more formal summary on the topic.

**Comment by gmac** [comment] 2021-02-05 14:02
Okay @tsteenkamp – I've expanded the "Combining Local and Remote Schemas" example with a sample Auth header flow in https://github.com/gmac/schema-stitching-handbook/pull/26. Feel free to reopen if you have additional questions.

**Closed as completed by gmac** 2021-02-05 14:02 UTC

**Comment by SantosOMartinez** [comment] 2021-04-13 05:00
How would this look like if the authorization method is using cookies. Such as with express-session?

**Comment by gmac** [comment] 2021-04-13 13:01
@SantosOMartinez Seems like about the same way as in that demo, right? The user is only ever authenticating with the gateway directly, and an expression of that authentication is transferred into GraphQL context and sent with subservice requests. Seems like you’d do the same thing with sessions. You could transfer session data from a request into context and send it as headers to subservices — this retains an expression of the user in subservice auth; or if you don’t care about specific users in subservices, then the user can just authenticate with the gateway and it can request to subservices using a machine-to-machine token.

I’d also mention that if your only vehicle for authentication is using sessions, that’s not terribly robust as a general-purpose API access pattern and you should consider expanding to support tokens.

**Comment by SantosOMartinez** [comment] 2021-04-13 14:50
I am currently using a token based authentication which has a short expiration time, and then I also send a refresh token to be used before the expiration of the authentication token to get a new one. This refresh token is being saved as an http only cookie that gets sent every so often to refresh the auth token to be used around the system. The issue is that I am unable to pass the cookie up the stream from the microservice once it is created to the end user through the api gateway.

I will provide some code below to highlight my issue:


index.js
```js
	const server = new ApolloServer({
		schema,
		formatError: (err) => new Error(err.message),
		context: ({ req }) => {
			return {
				req,
                               cookie: req.headers.cookie,
			};
		},
	});
```

index.js
```js
const createRemoteExecutableSchemas = async () => {
	let schemas = [];
	for (const api of graphqlApis) {
		const executor = makeRemoteExecutor(api.uri);
		const schema = await introspectSchema(executor);
		schemas.push({ schema, executor });
	}
	return schemas;
};
```

makeRemoteExecutioner.js
```js
export function makeRemoteExecutor(url) {
	return async ({ document, variables, context }) => {

		const query = typeof document === "string" ? document : print(document);
		const fetchResult = await fetch(url, {
			method: "POST",
			headers: {
				cookie: context?.cookie,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ query, variables }),
		});
		//console.log(fetchResult.headers); <-- if I console log this the cookie shows from the authentication microservice but how do I pass this up and set it to the users cookies.

		return fetchResult.json();
	};
}
```

Sorry in advanced I am fairly new to the backend.

**Comment by gmac** [comment] 2021-04-13 17:03
I don’t fully understand what you’re doing but it sounds like a pretty unconventional auth strategy. Subservices (ie: microservices) shouldn’t be auth providers that would ever issue a token, so there’s no reason that auth information should ever flow “upstream” going subservice > gateway > client. Sounds like you may want to start with some preliminary research into basic authentication patterns with a distributed system. In a nutshell, it works like this:

A system has some kind of “auth provider” service that handles all authentication concerns. This could be a third-party service like Auth0 or your own implementation (typically setup as an OAuth provider). Users always authenticate with the auth service directly. Then for making API requests, the user’s auth token is submitted as a header to the gateway and passed throughout the request chain, as documented in the handbook. Each service that receives the auth header then verifies it independently with the auth provider (or with a cached public key issued by the auth provider) before fulfilling its request. Note that subservices should always verify tokens themselves and not assume that the gateway verified the auth header for them.

**Comment by gmac** [comment] 2021-04-13 17:29
One followup thought is that the formal auth pattern described above may require services that don’t currently exist in your stack, which presents a barrier to entry. To overcome that initially, the quick-and-dirty alternative would be to just have the user authenticate once with the gateway, and have the gateway make all subservice requests using its own M2M token or shared secret, and possibly including the user ID as a header for authorization context. This is not a great long term solution, but it’s passable as a quick fix to get you up and running.

**Comment by SantosOMartinez** [comment] 2021-04-13 18:07
Thank you for your advice!

**Comment by tsteenkamp** [comment] 2021-04-13 19:33
What client and auth provider are you using? If you by any chance use keycloak or something similar as the auth provider and a Javascript SPA I'd recommend not handling the cookies directly / using them at all. Instead you should be able to issue a token on application startup and then attach that token via authorization headers on every graphql request to the api gateway. No need to handle cookies and sessions in your gateway, ofc you should validate the token by JWKS or similar in the gateway service and/or in all sub-services.

**Comment by gmac** [comment] 2021-04-13 22:07
Highly recommend the specific choice of JWT/JWKS within the OAuth flow

**Comment by yaacovCR** [comment] 2021-04-14 19:01
Agreeing with @gmac above, but to answer your question more specifically, it seems like you are asking an [`express-session`](https://www.npmjs.com/package/express-session) question in terms of how to set a value within the session.

It seems like it is done as follows:

```
return async ({ document, variables, context }) => {
		const query = typeof document === "string" ? document : print(document);
		const fetchResult = await fetch(url, {
			method: "POST",
			headers: {
				// not editing below for now, see comments below this code
				cookie: context?.cookie,
				"Content-Type": "application/json",
			},
			body: JSON.stringify({ query, variables }),
		});
		//YOUR QUESTION:
		//console.log(fetchResult.headers); <-- if I console log this the cookie shows from the authentication microservice
		//how do I pass this up and set it to the users cookies?
		// 
		// MY THOUGHT:
		const { authToken, refreshToken } = extractAuthTokenFromFetchResult(fetchResult);
		context.req.session.token = { authToken, refreshToken };
		return fetchResult.json();
	};
```

I believe the idea of `express-session` is you get access to a serializable session object which is transparently associated with the correct client via a cookie, but with the session data perhaps stored server side in any compatible store, such that you get to set and retrieve whatever values you want simply by modifying and reading the session object.

Note the comment above in terms of how you are passing the refreshToken to the downstream service. I am not addressing that here, I imagine you would use the Authorization header with the [bearer token scheme](https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml), and not just pass the cookie from the client.
